# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_host_host_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostuser',
            unique_together=set([]),
        ),
    ]
